import { useState, useRef, useCallback, useEffect } from 'react';
import { AppleDots } from './AppleDots';

interface CardSwiperProps {
  children: React.ReactNode[];
  cardWidth?: number;
  cardHeight?: number;
  sideScale?: number;
  sideOffset?: number;
  sideVerticalOffset?: number;
  initialIndex?: number;
  className?: string;
  fadeIn?: boolean;
  isPlaying?: boolean;
  onTogglePlay?: () => void;
  hideDots?: boolean;
  onIndexChange?: (index: number) => void;
  onUserSwipe?: () => void;
  onDragStart?: () => void;
  infinite?: boolean;
  onTap?: (index: number) => void;
}

export function CardSwiper({
  children,
  cardWidth = 230,
  cardHeight = 330,
  sideScale = 0.78,
  sideOffset = 40,
  sideVerticalOffset = 20,
  initialIndex = 0,
  className = '',
  fadeIn = true,
  isPlaying,
  onTogglePlay,
  hideDots = false,
  onIndexChange,
  onUserSwipe,
  onDragStart,
  infinite = false,
  onTap,
}: CardSwiperProps) {
  const [currentIndex, setCurrentIndex] = useState(initialIndex);
  const [dragOffset, setDragOffset] = useState(0);
  const [isDragging, setIsDragging] = useState(false);

  // === Refs to avoid stale closures ===
  const dragStartRef = useRef<{ x: number; time: number } | null>(null);
  const dragOffsetRef = useRef(0);
  const wasDraggingRef = useRef(false);
  const currentIndexRef = useRef(currentIndex);
  const recentTouchRef = useRef(false); // suppress synthetic mouse events after touch

  const total = children.length;

  // Keep ref in sync
  currentIndexRef.current = currentIndex;

  // Reset index when children change
  useEffect(() => {
    setCurrentIndex(0);
    setDragOffset(0);
    dragOffsetRef.current = 0;
    if (onIndexChange) onIndexChange(0);
  }, [total]);

  const wrapIndex = useCallback((index: number) => {
    if (!infinite) return Math.max(0, Math.min(total - 1, index));
    return ((index % total) + total) % total;
  }, [total, infinite]);

  const goTo = useCallback((index: number) => {
    const wrapped = wrapIndex(index);
    setCurrentIndex(wrapped);
    currentIndexRef.current = wrapped;
    setDragOffset(0);
    dragOffsetRef.current = 0;
    if (onIndexChange) onIndexChange(wrapped);
  }, [wrapIndex, onIndexChange]);

  const goNext = useCallback(() => {
    const ci = currentIndexRef.current;
    if (infinite) {
      goTo(ci + 1);
    } else {
      if (ci < total - 1) goTo(ci + 1);
      else { setDragOffset(0); dragOffsetRef.current = 0; }
    }
  }, [total, goTo, infinite]);

  const goPrev = useCallback(() => {
    const ci = currentIndexRef.current;
    if (infinite) {
      goTo(ci - 1);
    } else {
      if (ci > 0) goTo(ci - 1);
      else { setDragOffset(0); dragOffsetRef.current = 0; }
    }
  }, [total, goTo, infinite]);

  // === Touch handlers (ref-based to avoid stale closures) ===
  const handleTouchStart = useCallback((e: React.TouchEvent) => {
    recentTouchRef.current = true;
    dragStartRef.current = { x: e.touches[0].clientX, time: Date.now() };
    wasDraggingRef.current = false;
  }, []);

  const handleTouchMove = useCallback((e: React.TouchEvent) => {
    if (!dragStartRef.current) return;
    const dx = e.touches[0].clientX - dragStartRef.current.x;

    if (Math.abs(dx) > 8) {
      e.preventDefault();
    }

    let offset = dx;
    const ci = currentIndexRef.current;
    if (!infinite && ((ci === 0 && dx > 0) || (ci === total - 1 && dx < 0))) {
      offset = dx * 0.25;
    }

    if (Math.abs(dx) > 8) {
      if (!wasDraggingRef.current && onDragStart) onDragStart();
      wasDraggingRef.current = true;
      setDragOffset(offset);
      dragOffsetRef.current = offset;
      setIsDragging(true);
    }
  }, [total, infinite, onDragStart]);

  const handleTouchEnd = useCallback(() => {
    if (!dragStartRef.current) return;
    const elapsed = Date.now() - dragStartRef.current.time;
    const currentDragOffset = dragOffsetRef.current;
    const velocity = Math.abs(currentDragOffset) / Math.max(elapsed, 1);
    const didDrag = wasDraggingRef.current;

    if (didDrag && (Math.abs(currentDragOffset) > 50 || velocity > 0.35)) {
      if (currentDragOffset < 0) goNext();
      else goPrev();
      if (onUserSwipe) onUserSwipe();
    } else if (!didDrag && elapsed < 400 && onTap) {
      // Pure tap: no drag movement at all
      onTap(currentIndexRef.current);
    } else {
      setDragOffset(0);
      dragOffsetRef.current = 0;
    }

    dragStartRef.current = null;
    wasDraggingRef.current = false;
    setIsDragging(false);
    // Keep recentTouchRef true to block synthetic mouse events; reset after delay
    setTimeout(() => { recentTouchRef.current = false; }, 500);
  }, [goNext, goPrev, onUserSwipe, onTap]);

  // Mouse drag (for desktop testing)
  const mouseDownRef = useRef(false);
  const handleMouseDown = useCallback((e: React.MouseEvent) => {
    // Block synthetic mouse events generated by mobile browsers after touch
    if (recentTouchRef.current) return;
    e.preventDefault();
    dragStartRef.current = { x: e.clientX, time: Date.now() };
    mouseDownRef.current = true;
    wasDraggingRef.current = false;
    setIsDragging(true);
    if (onDragStart) onDragStart();
  }, [onDragStart]);

  useEffect(() => {
    if (!mouseDownRef.current) return;
    const handleMouseMove = (e: MouseEvent) => {
      if (!dragStartRef.current) return;
      const dx = e.clientX - dragStartRef.current.x;
      let offset = dx;
      const ci = currentIndexRef.current;
      if (!infinite && ((ci === 0 && dx > 0) || (ci === total - 1 && dx < 0))) {
        offset = dx * 0.25;
      }
      if (Math.abs(dx) > 8) wasDraggingRef.current = true;
      setDragOffset(offset);
      dragOffsetRef.current = offset;
    };
    const handleMouseUp = () => {
      mouseDownRef.current = false;
      const elapsed = Date.now() - (dragStartRef.current?.time || Date.now());
      const currentDragOffset = dragOffsetRef.current;
      const velocity = Math.abs(currentDragOffset) / Math.max(elapsed, 1);
      if (Math.abs(currentDragOffset) > 50 || velocity > 0.35) {
        if (currentDragOffset < 0) goNext();
        else goPrev();
        if (onUserSwipe) onUserSwipe();
      } else {
        setDragOffset(0);
        dragOffsetRef.current = 0;
      }
      dragStartRef.current = null;
      wasDraggingRef.current = false;
      setIsDragging(false);
    };
    window.addEventListener('mousemove', handleMouseMove);
    window.addEventListener('mouseup', handleMouseUp);
    return () => {
      window.removeEventListener('mousemove', handleMouseMove);
      window.removeEventListener('mouseup', handleMouseUp);
    };
  }, [isDragging, currentIndex, total, goNext, goPrev, infinite, onUserSwipe]);

  // Keyboard
  useEffect(() => {
    const handleKey = (e: KeyboardEvent) => {
      if (e.key === 'ArrowRight') goNext();
      else if (e.key === 'ArrowLeft') goPrev();
    };
    window.addEventListener('keydown', handleKey);
    return () => window.removeEventListener('keydown', handleKey);
  }, [goNext, goPrev]);

  // 카드 스타일 계산 (커버플로우)
  const sideCardWidth = cardWidth * sideScale;
  const totalWidth = sideCardWidth + cardWidth + sideCardWidth - sideOffset * 2;

  const getCardStyle = (index: number): React.CSSProperties | null => {
    let diff = index - currentIndex;

    if (infinite && total > 2) {
      if (diff > total / 2) diff -= total;
      if (diff < -total / 2) diff += total;
    }

    if (Math.abs(diff) > 2) return null;

    const isCenter = diff === 0;
    const absDiff = Math.abs(diff);

    let scale = isCenter ? 1 : sideScale * (absDiff === 1 ? 1 : 0.6);
    let opacity = isCenter ? 1 : absDiff === 1 ? 0.7 : 0;
    let zIndex = isCenter ? 10 : absDiff === 1 ? 5 : 1;

    const centerX = totalWidth / 2 - cardWidth / 2;
    let x: number;
    if (isCenter) {
      x = centerX;
    } else if (diff < 0) {
      x = centerX - (cardWidth / 2 + sideCardWidth / 2 - sideOffset) * absDiff;
    } else {
      x = centerX + (cardWidth / 2 + sideCardWidth / 2 - sideOffset) * absDiff;
    }

    if (isDragging) {
      x += dragOffset * 0.8;
    }

    return {
      position: 'absolute',
      left: 0,
      top: 0,
      width: cardWidth,
      height: cardHeight,
      transform: `translateX(${x}px) translateY(${(cardHeight - cardHeight * scale) / 2 - sideVerticalOffset * absDiff}px) scale(${scale})`,
      transformOrigin: 'center center',
      transition: isDragging ? 'none' : 'transform 0.4s cubic-bezier(0.22, 1, 0.36, 1), opacity 0.4s ease',
      opacity,
      zIndex,
      pointerEvents: isCenter ? 'auto' : 'none',
      filter: isCenter ? 'none' : 'brightness(0.92)',
      willChange: 'transform, opacity',
    } as React.CSSProperties;
  };

  if (total === 0) return null;

  return (
    <div
      className={`flex flex-col items-center gap-2 transition-opacity duration-500 ${className}`}
      style={{ opacity: fadeIn ? 1 : 0 }}
    >
      {/* 카드 영역 */}
      <div
        className="relative select-none overflow-visible"
        style={{
          width: totalWidth,
          height: cardHeight,
          touchAction: 'none',
        }}
        onTouchStart={handleTouchStart}
        onTouchMove={handleTouchMove}
        onTouchEnd={handleTouchEnd}
        onMouseDown={handleMouseDown}
      >
        {children.map((child, index) => {
          const style = getCardStyle(index);
          if (!style) return null;
          return (
            <div key={index} style={style}>
              {child}
            </div>
          );
        })}
      </div>

      {/* 네비게이션 — 인스타그램 스타일 도트 */}
      {(!hideDots || onTogglePlay !== undefined) && (
        <div className="flex items-center justify-center gap-3">
          {!hideDots && (
            <AppleDots
              total={total}
              current={currentIndex}
              onDotClick={(idx) => goTo(idx)}
            />
          )}

          {onTogglePlay !== undefined && (
            <button
              onClick={onTogglePlay}
              className="w-9 h-9 flex items-center justify-center rounded-full bg-white shadow-md border border-gray-200 text-gray-600 cursor-pointer transition-colors hover:bg-gray-50"
              style={{
                borderColor: isPlaying ? '#d1d5db' : '#002BFF',
                borderWidth: isPlaying ? '1px' : '2px',
              }}
              aria-label={isPlaying ? '일시정지' : '재생'}
            >
              {isPlaying ? (
                <svg width="14" height="14" viewBox="0 0 24 24" fill="#002BFF" stroke="none">
                  <rect x="6" y="4" width="4" height="16" rx="1.5" />
                  <rect x="14" y="4" width="4" height="16" rx="1.5" />
                </svg>
              ) : (
                <svg width="14" height="14" viewBox="0 0 24 24" fill="#002BFF" stroke="none">
                  <polygon points="7,4 21,12 7,20" />
                </svg>
              )}
            </button>
          )}
        </div>
      )}
    </div>
  );
}